manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name : hidergo
      url-base : https://github.com/hidergo
  projects:
    - name: zmk
      remote: hidergo
      revision: boardpilot
      import: app/west.yml
  self:
    path: config
